<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FaskesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('faskes')->insert([
            [
                'nama' => 'RSUD Kota Depok',
                'nama_pengelola' => 'Pemerintah Kota Depok',
                'alamat' => 'Jl. Raya Sawangan No.2, Pancoran MAS, Kota Depok, Jawa Barat 16436',
                'website' => 'http://rsud.depok.go.id',
                'email' => 'info@rsud.depok.go.id',
                'kabkota_id' => 1,
                'rating' => 5,
                'latitude' => -6.398716,
                'longitude' => 106.818626,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RS Hermina Depok',
                'nama_pengelola' => 'RS Hermina Group',
                'alamat' => 'Jl. Siliwangi No.50, Depok, Pancoran MAS, Kota Depok, Jawa Barat 16436',
                'website' => 'http://herminahospitals.com',
                'email' => 'info@herminahospitals.com',
                'kabkota_id' => 1,
                'rating' => 4,
                'latitude' => -6.379782,
                'longitude' => 106.834567,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RSU Bunda Margonda',
                'nama_pengelola' => 'PT Bunda Medik',
                'alamat' => 'Jl. Margonda Raya No.28, Pondok Cina, Beji, Kota Depok, Jawa Barat 16424',
                'website' => 'http://bundamedik.com',
                'email' => 'info@bundamedik.com',
                'kabkota_id' => 1,
                'rating' => 5,
                'latitude' => -6.369028,
                'longitude' => 106.831991,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'Puskesmas Beji',
                'nama_pengelola' => 'Dinas Kesehatan Kota Depok',
                'alamat' => 'Jl. Jawa Raya No.8, Beji Timur, Beji, Kota Depok, Jawa Barat 16422',
                'website' => 'http://puskesmasbeji.depok.go.id',
                'email' => 'info@puskesmasbeji.depok.go.id',
                'kabkota_id' => 1,
                'rating' => 3,
                'latitude' => -6.375248,
                'longitude' => 106.839287,
                'jenis_faskes_id' => 2,
                'kategori_id' => 2,
            ],
            [
                'nama' => 'Klinik Pratama Harapan Kita',
                'nama_pengelola' => 'Yayasan Harapan Kita',
                'alamat' => 'Jl. Margonda Raya No.348, Kemiri Muka, Beji, Kota Depok, Jawa Barat 16424',
                'website' => 'http://klinikharapankita.com',
                'email' => 'info@klinikharapankita.com',
                'kabkota_id' => 1,
                'rating' => 4,
                'latitude' => -6.385911,
                'longitude' => 106.826226,
                'jenis_faskes_id' => 3,
                'kategori_id' => 2,
            ],
            [
                'nama' => 'RSUD Kota Bogor',
                'nama_pengelola' => 'Pemerintah Kota Bogor',
                'alamat' => 'Jl. Dr. Semeru No.120, Menteng, Kota Bogor, Jawa Barat 16111',
                'website' => 'http://rsud.kotabogor.go.id',
                'email' => 'info@rsud.kotabogor.go.id',
                'kabkota_id' => 2,
                'rating' => 5,
                'latitude' => -6.595038,
                'longitude' => 106.799820,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RS PMI Bogor',
                'nama_pengelola' => 'Palang Merah Indonesia',
                'alamat' => 'Jl. Pajajaran Indah V No.97, Baranangsiang, Bogor Timur, Kota Bogor, Jawa Barat 16143',
                'website' => 'http://rspmibogor.or.id',
                'email' => 'info@rspmibogor.or.id',
                'kabkota_id' => 2,
                'rating' => 4,
                'latitude' => -6.591732,
                'longitude' => 106.808616,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RS Azra',
                'nama_pengelola' => 'RS Azra Group',
                'alamat' => 'Jl. Raya Pajajaran No.219, Bantarjati, Bogor Utara, Kota Bogor, Jawa Barat 16153',
                'website' => 'http://rsazra.com',
                'email' => 'info@rsazra.com',
                'kabkota_id' => 2,
                'rating' => 4,
                'latitude' => -6.581468,
                'longitude' => 106.806908,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'Puskesmas Bogor Tengah',
                'nama_pengelola' => 'Dinas Kesehatan Kota Bogor',
                'alamat' => 'Jl. Kapten Muslihat No.22, Pabaton, Bogor Tengah, Kota Bogor, Jawa Barat 16121',
                'website' => 'http://puskesmasbogortengah.go.id',
                'email' => 'info@puskesmasbogortengah.go.id',
                'kabkota_id' => 2,
                'rating' => 3,
                'latitude' => -6.595928,
                'longitude' => 106.791679,
                'jenis_faskes_id' => 2,
                'kategori_id' => 2,
            ],
            [
                'nama' => 'Klinik Kimia Farma Pajajaran',
                'nama_pengelola' => 'PT Kimia Farma',
                'alamat' => 'Jl. Raya Pajajaran No.80, Baranangsiang, Bogor Timur, Kota Bogor, Jawa Barat 16143',
                'website' => 'http://klinik.kimiafarma.co.id',
                'email' => 'info@kimiafarma.co.id',
                'kabkota_id' => 2,
                'rating' => 4,
                'latitude' => -6.590338,
                'longitude' => 106.809734,
                'jenis_faskes_id' => 3,
                'kategori_id' => 2,
            ],
            [
                'nama' => 'RS Cipto Mangunkusumo',
                'nama_pengelola' => 'Kementerian Kesehatan RI',
                'alamat' => 'Jl. Diponegoro No.71, Kenari, Senen, Kota Jakarta Pusat, DKI Jakarta 10430',
                'website' => 'http://rscm.co.id',
                'email' => 'info@rscm.co.id',
                'kabkota_id' => 3,
                'rating' => 5,
                'latitude' => -6.193631,
                'longitude' => 106.847418,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RSUP Fatmawati',
                'nama_pengelola' => 'Kementerian Kesehatan RI',
                'alamat' => 'Jl. RS Fatmawati Raya No.4, Cilandak, Kota Jakarta Selatan, DKI Jakarta 12430',
                'website' => 'http://rsupfatmawati.id',
                'email' => 'info@rsupfatmawati.id',
                'kabkota_id' => 3,
                'rating' => 5,
                'latitude' => -6.289505,
                'longitude' => 106.798678,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'RS MMC Jakarta',
                'nama_pengelola' => 'PT Medikaloka',
                'alamat' => 'Jl. HR Rasuna Said Kav C-20, Karet Kuningan, Setiabudi, Kota Jakarta Selatan, DKI Jakarta 12940',
                'website' => 'http://mmc-hospital.com',
                'email' => 'info@mmc-hospital.com',
                'kabkota_id' => 3,
                'rating' => 4,
                'latitude' => -6.222456,
                'longitude' => 106.833050,
                'jenis_faskes_id' => 1,
                'kategori_id' => 1,
            ],
            [
                'nama' => 'Puskesmas Gambir',
                'nama_pengelola' => 'Dinas Kesehatan DKI Jakarta',
                'alamat' => 'Jl. Tanah Abang I No.1, Petojo Selatan, Gambir, Kota Jakarta Pusat, DKI Jakarta 10160',
                'website' => 'http://puskesmasgambir.jakarta.go.id',
                'email' => 'info@puskesmasgambir.jakarta.go.id',
                'kabkota_id' => 3,
                'rating' => 3,
                'latitude' => -6.181232,
                'longitude' => 106.819183,
                'jenis_faskes_id' => 2,
                'kategori_id' => 2,
            ],
            [
                'nama' => 'Klinik Mitra Keluarga Kemayoran',
                'nama_pengelola' => 'PT Mitra Keluarga',
                'alamat' => 'Jl. HBR Motik Blok B-8 No.4, Kemayoran, Kota Jakarta Pusat, DKI Jakarta 10610',
                'website' => 'http://mitrakeluarga.com',
                'email' => 'info@mitrakeluarga.com',
                'kabkota_id' => 3,
                'rating' => 4,
                'latitude' => -6.157276,
                'longitude' => 106.845303,
                'jenis_faskes_id' => 3,
                'kategori_id' => 2,
            ],
        ]);
    }
}
?>
